name: Echo issue -> PR (single .md file, authored by submitter)

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  to-pr:
    # Run only when the issue has the 'echo' label
    if: contains(github.event.issue.labels.*.name, 'echo')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare echo info
        id: f
        shell: bash
        run: |
          set -euo pipefail
          TITLE="${{ github.event.issue.title }}"
          SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g;s/^-+|-+$//g')
          mkdir -p echoes
          N=$(ls echoes 2>/dev/null | grep -E '^[0-9]{4}-' | wc -l | xargs || true)
          printf -v ID "%04d" $((N+1))
          FILE="echoes/${ID}-${SLUG}.md"
          YEAR=$(date +%Y)
          {
            echo "title=$TITLE"
            echo "slug=$SLUG"
            echo "year=$YEAR"
            echo "id=$ID"
            echo "file=$FILE"
          } >> "$GITHUB_OUTPUT"

      - name: Determine author identity
        id: author
        shell: bash
        run: |
          set -euo pipefail
          LOGIN='${{ github.event.issue.user.login }}'
          IDNUM='${{ github.event.issue.user.id }}'
          EMAIL="${IDNUM}+${LOGIN}@users.noreply.github.com"
          echo "name=$LOGIN"  >> "$GITHUB_OUTPUT"
          echo "email=$EMAIL" >> "$GITHUB_OUTPUT"

      - name: Create branch and write markdown
        shell: bash
        env:
          TITLE: ${{ steps.f.outputs.title }}
          SLUG:  ${{ steps.f.outputs.slug }}
          YEAR:  ${{ steps.f.outputs.year }}
          ID:    ${{ steps.f.outputs.id }}
          FILE:  ${{ steps.f.outputs.file }}
          AUTHOR_NAME:  ${{ steps.author.outputs.name }}
          AUTHOR_EMAIL: ${{ steps.author.outputs.email }}
          GH_REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          set -euo pipefail
          BR="echo/${SLUG}-${ID}"
          git switch -c "$BR"

          # Pull issue body JSON
          curl -s -H "Accept: application/vnd.github+json" \
            "$GITHUB_API_URL/repos/$GH_REPO/issues/$ISSUE_NUMBER" > /tmp/issue.json

          python - <<'PY'
import json, re, os
i=json.load(open("/tmp/issue.json"))
body=i.get("body") or ""
def grab(h):
    m=re.search(rf"(?mi)^###\s*{re.escape(h)}\s*$\n+(.+?)(?:\n###|\Z)", body, re.S)
    return (m.group(1).strip() if m else "")
title=os.environ["TITLE"]
id_=int(os.environ["ID"])
author=i["user"]["login"]
year=os.environ["YEAR"]
created=os.popen("date +%F").read().strip()
content=f"""# {title}

**Echo ID:** {id_:04d}
**Year:** {year}
**Created:** {created}
**Author:** @{author}

## Problem
{grab("Problem")}

## Proposal
{grab("Proposal")}

## Notes
{grab("Extra context / links")}
"""
os.makedirs(os.path.dirname(os.environ["FILE"]), exist_ok=True)
open(os.environ["FILE"], "w", encoding="utf-8").write(content)
PY

          git add "${FILE}"

          # Commit as the submitter (author & committer)
          git config user.name  "${AUTHOR_NAME}"
          git config user.email "${AUTHOR_EMAIL}"
          git commit \
            --author="${AUTHOR_NAME} <${AUTHOR_EMAIL}>" \
            -m "echo(${ID}): ${TITLE}"

          git push -u origin "$BR"

      - name: Open PR
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          gh pr create \
            --base main \
            --head "echo/${{ steps.f.outputs.slug }}-${{ steps.f.outputs.id }}" \
            --title "Echo: ${{ steps.f.outputs.id }} - ${{ steps.f.outputs.title }}" \
            --body "Auto-generated from issue #${{ github.event.issue.number }} by @${{ github.event.issue.user.login }}"
